#ifndef __UTILS_NET_NET_PROTO_H__
#define __UTILS_NET_NET_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from utils/net/net.c  */

int net_run_function(struct net_context *ctx,
			int argc, const char **argv,
			const struct net_functable *functable, 
			int (*usage_fn)(struct net_context *ctx, int argc, const char **argv));
int net_run_usage(struct net_context *ctx,
			int argc, const char **argv,
			const struct net_functable *functable);
int net_help(struct net_context *ctx, const struct net_functable *ftable);

/* The following definitions come from utils/net/net_password.c  */

int net_password(struct net_context *ctx, int argc, const char **argv) ;
int net_password_usage(struct net_context *ctx, int argc, const char **argv);

/* The following definitions come from utils/net/net_time.c  */

int net_time(struct net_context *ctx, int argc, const char **argv);
int net_time_usage(struct net_context *ctx, int argc, const char **argv);

/* The following definitions come from utils/net/net_join.c  */

int net_join(struct net_context *ctx, int argc, const char **argv) ;
int net_join_usage(struct net_context *ctx, int argc, const char **argv);
int net_join_help(struct net_context *ctx, int argc, const char **argv);

/* The following definitions come from utils/net/net_vampire.c  */

int net_samdump(struct net_context *ctx, int argc, const char **argv) ;
int net_samdump_usage(struct net_context *ctx, int argc, const char **argv);
int net_samdump_help(struct net_context *ctx, int argc, const char **argv);
int net_samsync_ldb(struct net_context *ctx, int argc, const char **argv) ;
int net_samsync_ldb_usage(struct net_context *ctx, int argc, const char **argv);
int net_samsync_ldb_help(struct net_context *ctx, int argc, const char **argv);

/* The following definitions come from utils/net/net_user.c  */

int net_user(struct net_context *ctx, int argc, const char **argv);
int net_user_usage(struct net_context *ctx, int argc, const char **argv);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __UTILS_NET_NET_PROTO_H__ */

