#ifndef __TORTURE_PROTO_H__
#define __TORTURE_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from torture/torture.c  */

bool torture_register_suite(struct torture_suite *suite);
struct torture_context *torture_context_init(TALLOC_CTX *mem_ctx, 
											 const char *known_failures_file, 
											 const struct torture_ui_ops *ui_ops);
int torture_init(void);

/* The following definitions come from torture/subunit.c  */

struct torture_suite *torture_subunit_suite_create(TALLOC_CTX *mem_ctx,
														 const char *path);
bool torture_subunit_load_testsuites(const char *directory, bool recursive, 
									struct torture_suite *parent);
bool torture_subunit_run_suite(struct torture_context *context, 
					   struct torture_suite *suite);

/* The following definitions come from torture/ui.c  */

void torture_comment(struct torture_context *context, const char *comment, ...);
void torture_result(struct torture_context *context, 
					enum torture_result result, const char *fmt, ...);
struct torture_suite *torture_suite_create(TALLOC_CTX *ctx, const char *name);
void torture_tcase_set_fixture(struct torture_tcase *tcase, 
		BOOL (*setup) (struct torture_context *, void **),
		BOOL (*teardown) (struct torture_context *, void *));
struct torture_test *torture_tcase_add_test(struct torture_tcase *tcase, 
						const char *name, 
						bool (*run) (struct torture_context *, 
									 const void *tcase_data,
									 const void *test_data),
						const void *data);
struct torture_tcase *torture_suite_add_tcase(struct torture_suite *suite, 
							 const char *name);
BOOL torture_run_suite(struct torture_context *context, 
					   struct torture_suite *suite);
void torture_ui_test_start(struct torture_context *context,
							   struct torture_tcase *tcase,
							   struct torture_test *test);
int str_list_match(const char *name, char **list);
void torture_ui_test_result(struct torture_context *context,
								enum torture_result result,
								const char *comment);
BOOL torture_run_tcase(struct torture_context *context, 
					   struct torture_tcase *tcase);
BOOL torture_run_test(struct torture_context *context, 
					  struct torture_tcase *tcase,
					  struct torture_test *test);
int torture_setting_int(struct torture_context *test, const char *name, 
							int default_value);
bool torture_setting_bool(struct torture_context *test, const char *name, 
							bool default_value);
const char *torture_setting_string(struct torture_context *test, const char *name, 
							const char *default_value);
struct torture_tcase *torture_suite_add_simple_tcase(
					struct torture_suite *suite, 
					const char *name,
					bool (*run) (struct torture_context *test, const void *),
					const void *data);
struct torture_tcase *torture_suite_add_simple_test(
					struct torture_suite *suite, 
					const char *name,
					bool (*run) (struct torture_context *test));
bool torture_suite_add_suite(struct torture_suite *suite, 
							 struct torture_suite *child);
struct torture_suite *torture_find_suite(struct torture_suite *parent, 
										 const char *name);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __TORTURE_PROTO_H__ */

