#ifndef __LIB_REGISTRY_REG_BACKEND_RPC_H__
#define __LIB_REGISTRY_REG_BACKEND_RPC_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from lib/registry/reg_backend_rpc.c  */

_PUBLIC_ WERROR reg_open_remote(struct registry_context **ctx, struct auth_session_info *session_info, struct cli_credentials *credentials, 
		       const char *location, struct event_context *ev);
NTSTATUS registry_rpc_init(void);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __LIB_REGISTRY_REG_BACKEND_RPC_H__ */

