#ifndef __WINBIND_WB_HELPER_H__
#define __WINBIND_WB_HELPER_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from winbind/wb_async_helpers.c  */

struct composite_context *wb_get_schannel_creds_send(TALLOC_CTX *mem_ctx,
						     struct cli_credentials *wks_creds,
						     struct smbcli_tree *tree,
						     struct event_context *ev);
NTSTATUS wb_get_schannel_creds_recv(struct composite_context *c,
				    TALLOC_CTX *mem_ctx,
				    struct dcerpc_pipe **netlogon_pipe);
NTSTATUS wb_get_schannel_creds(TALLOC_CTX *mem_ctx,
			       struct cli_credentials *wks_creds,
			       struct smbcli_tree *tree,
			       struct event_context *event_ctx,
			       struct dcerpc_pipe **netlogon_pipe);
struct composite_context *wb_lsa_lookupsids_send(TALLOC_CTX *mem_ctx,
						 struct dcerpc_pipe *lsa_pipe,
						 struct policy_handle *handle,
						 int num_sids,
						 const struct dom_sid **sids);
NTSTATUS wb_lsa_lookupsids_recv(struct composite_context *c,
				TALLOC_CTX *mem_ctx,
				struct wb_sid_object ***names);
NTSTATUS wb_lsa_lookupsids(TALLOC_CTX *mem_ctx,
			   struct dcerpc_pipe *lsa_pipe,
			   struct policy_handle *handle,
			   int num_sids, const struct dom_sid **sids,
			   struct wb_sid_object ***names);
struct composite_context *wb_lsa_lookupnames_send(TALLOC_CTX *mem_ctx,
						  struct dcerpc_pipe *lsa_pipe,
						  struct policy_handle *handle,
						  int num_names,
						  const char **names);
NTSTATUS wb_lsa_lookupnames_recv(struct composite_context *c,
				 TALLOC_CTX *mem_ctx,
				 struct wb_sid_object ***sids);
NTSTATUS wb_lsa_lookupnames(TALLOC_CTX *mem_ctx,
			    struct dcerpc_pipe *lsa_pipe, 
			    struct policy_handle *handle,
			    int num_names, const char **names,
			    struct wb_sid_object ***sids);
struct composite_context *wb_samr_userdomgroups_send(TALLOC_CTX *mem_ctx,
						     struct dcerpc_pipe *samr_pipe,
						     struct policy_handle *domain_handle,
						     uint32_t rid);
NTSTATUS wb_samr_userdomgroups_recv(struct composite_context *ctx,
				    TALLOC_CTX *mem_ctx,
				    int *num_rids, uint32_t **rids);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __WINBIND_WB_HELPER_H__ */

