#ifndef __RPC_SERVER_SRVSVC_PROTO_H__
#define __RPC_SERVER_SRVSVC_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from rpc_server/srvsvc/dcesrv_srvsvc.c  */


/* The following definitions come from rpc_server/srvsvc/srvsvc_ntvfs.c  */

struct socket_address *srvsvc_get_my_addr(void *p, TALLOC_CTX *mem_ctx);
struct socket_address *srvsvc_get_peer_addr(void *p, TALLOC_CTX *mem_ctx);
NTSTATUS srvsvc_create_ntvfs_context(struct dcesrv_call_state *dce_call,
				     TALLOC_CTX *mem_ctx,
				     const char *share,
				     struct ntvfs_context **_ntvfs);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __RPC_SERVER_SRVSVC_PROTO_H__ */

