/* header auto-generated by pidl */

#ifndef _HEADER_frsapi
#define _HEADER_frsapi


struct FRSAPI_VERIFY_PROMOTION {
	int _dummy_element;
};


struct FRSAPI_PROMOTION_STATUS {
	int _dummy_element;
};


struct FRSAPI_START_DEMOTION {
	int _dummy_element;
};


struct FRSAPI_COMMIT_DEMOTION {
	int _dummy_element;
};


struct FRSAPI_SET_DS_POLLING_INTERVAL_W {
	int _dummy_element;
};


struct FRSAPI_GET_DS_POLLING_INTERVAL_W {
	int _dummy_element;
};


struct FRSAPI_VERIFY_PROMOTION_W {
	int _dummy_element;
};


struct FRSAPI_INFO_W {
	int _dummy_element;
};


struct FRSAPI_IS_PATH_REPLICATED {
	int _dummy_element;
};


struct FRSAPI_WRITER_COMMAND {
	int _dummy_element;
};

#endif /* _HEADER_frsapi */
