/* parser auto-generated by pidl */

#include "includes.h"
#include "libcli/util/nterr.h"
#include "librpc/gen_ndr/ndr_misc.h"
#include "librpc/gen_ndr/ndr_dcerpc.h"
#include "librpc/rpc/dcerpc.h"
#include "librpc/gen_ndr/ndr_protected_storage.h"

static NTSTATUS ndr_push_ps_XXX(struct ndr_push *ndr, int flags, const struct ps_XXX *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_WERROR(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_ps_XXX(struct ndr_pull *ndr, int flags, struct ps_XXX *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_WERROR(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_ps_XXX(struct ndr_print *ndr, const char *name, int flags, const struct ps_XXX *r)
{
	ndr_print_struct(ndr, name, "ps_XXX");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "ps_XXX");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "ps_XXX");
		ndr->depth++;
		ndr_print_WERROR(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static const struct dcerpc_interface_call protected_storage_calls[] = {
	{
		"ps_XXX",
		sizeof(struct ps_XXX),
		(ndr_push_flags_fn_t) ndr_push_ps_XXX,
		(ndr_pull_flags_fn_t) ndr_pull_ps_XXX,
		(ndr_print_function_t) ndr_print_ps_XXX,
		False,
	},
	{ NULL, 0, NULL, NULL, NULL, False }
};

static const char * const protected_storage_endpoint_strings[] = {
	"ncacn_np:[\\pipe\\protected_storage]", 
};

static const struct dcerpc_endpoint_list protected_storage_endpoints = {
	.count	= 1,
	.names	= protected_storage_endpoint_strings
};

static const char * const protected_storage_authservice_strings[] = {
	"host", 
};

static const struct dcerpc_authservice_list protected_storage_authservices = {
	.count	= 1,
	.names	= protected_storage_authservice_strings
};


const struct dcerpc_interface_table dcerpc_table_protected_storage = {
	.name		= "protected_storage",
	.syntax_id	= {
		{0xc9378ff1,0x16f7,0x11d0,{0xa0,0xb2},{0x00,0xaa,0x00,0x61,0x42,0x6a}},
		DCERPC_PROTECTED_STORAGE_VERSION
	},
	.helpstring	= DCERPC_PROTECTED_STORAGE_HELPSTRING,
	.num_calls	= 1,
	.calls		= protected_storage_calls,
	.endpoints	= &protected_storage_endpoints,
	.authservices	= &protected_storage_authservices
};

