/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_dnsserver.h"
#include "librpc/gen_ndr/ndr_dnsserver_c.h"

/* dnsserver - client functions generated by pidl */


struct rpc_request *dcerpc_dnsserver_foo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct dnsserver_foo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(dnsserver_foo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_dnsserver, DCERPC_DNSSERVER_FOO, mem_ctx, r);
}

NTSTATUS dcerpc_dnsserver_foo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct dnsserver_foo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_dnsserver_foo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(dnsserver_foo, r);		
	}

	return status;
}
