/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_eventlog.h"
#include "librpc/gen_ndr/ndr_eventlog_c.h"

/* eventlog - client functions generated by pidl */


struct rpc_request *dcerpc_eventlog_ClearEventLogW_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ClearEventLogW *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_ClearEventLogW, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_CLEAREVENTLOGW, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_ClearEventLogW(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ClearEventLogW *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_ClearEventLogW_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_ClearEventLogW, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_BackupEventLogW_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_BackupEventLogW *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_BackupEventLogW, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_BACKUPEVENTLOGW, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_BackupEventLogW(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_BackupEventLogW *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_BackupEventLogW_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_BackupEventLogW, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_CloseEventLog_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_CloseEventLog *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_CloseEventLog, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_CLOSEEVENTLOG, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_CloseEventLog(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_CloseEventLog *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_CloseEventLog_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_CloseEventLog, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_DeregisterEventSource_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_DeregisterEventSource *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_DeregisterEventSource, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_DEREGISTEREVENTSOURCE, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_DeregisterEventSource(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_DeregisterEventSource *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_DeregisterEventSource_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_DeregisterEventSource, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_GetNumRecords_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_GetNumRecords *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_GetNumRecords, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_GETNUMRECORDS, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_GetNumRecords(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_GetNumRecords *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_GetNumRecords_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_GetNumRecords, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_GetOldestRecord_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_GetOldestRecord *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_GetOldestRecord, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_GETOLDESTRECORD, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_GetOldestRecord(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_GetOldestRecord *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_GetOldestRecord_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_GetOldestRecord, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_ChangeNotify_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ChangeNotify *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_ChangeNotify, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_CHANGENOTIFY, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_ChangeNotify(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ChangeNotify *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_ChangeNotify_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_ChangeNotify, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_OpenEventLogW_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenEventLogW *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_OpenEventLogW, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_OPENEVENTLOGW, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_OpenEventLogW(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenEventLogW *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_OpenEventLogW_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_OpenEventLogW, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_RegisterEventSourceW_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_RegisterEventSourceW *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_RegisterEventSourceW, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_REGISTEREVENTSOURCEW, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_RegisterEventSourceW(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_RegisterEventSourceW *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_RegisterEventSourceW_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_RegisterEventSourceW, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_OpenBackupEventLogW_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenBackupEventLogW *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_OpenBackupEventLogW, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_OPENBACKUPEVENTLOGW, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_OpenBackupEventLogW(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenBackupEventLogW *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_OpenBackupEventLogW_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_OpenBackupEventLogW, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_ReadEventLogW_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReadEventLogW *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_ReadEventLogW, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_READEVENTLOGW, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_ReadEventLogW(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReadEventLogW *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_ReadEventLogW_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_ReadEventLogW, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_ReportEventW_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReportEventW *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_ReportEventW, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_REPORTEVENTW, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_ReportEventW(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReportEventW *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_ReportEventW_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_ReportEventW, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_ClearEventLogA_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ClearEventLogA *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_ClearEventLogA, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_CLEAREVENTLOGA, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_ClearEventLogA(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ClearEventLogA *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_ClearEventLogA_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_ClearEventLogA, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_BackupEventLogA_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_BackupEventLogA *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_BackupEventLogA, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_BACKUPEVENTLOGA, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_BackupEventLogA(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_BackupEventLogA *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_BackupEventLogA_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_BackupEventLogA, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_OpenEventLogA_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenEventLogA *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_OpenEventLogA, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_OPENEVENTLOGA, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_OpenEventLogA(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenEventLogA *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_OpenEventLogA_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_OpenEventLogA, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_RegisterEventSourceA_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_RegisterEventSourceA *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_RegisterEventSourceA, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_REGISTEREVENTSOURCEA, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_RegisterEventSourceA(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_RegisterEventSourceA *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_RegisterEventSourceA_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_RegisterEventSourceA, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_OpenBackupEventLogA_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenBackupEventLogA *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_OpenBackupEventLogA, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_OPENBACKUPEVENTLOGA, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_OpenBackupEventLogA(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_OpenBackupEventLogA *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_OpenBackupEventLogA_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_OpenBackupEventLogA, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_ReadEventLogA_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReadEventLogA *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_ReadEventLogA, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_READEVENTLOGA, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_ReadEventLogA(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReadEventLogA *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_ReadEventLogA_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_ReadEventLogA, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_ReportEventA_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReportEventA *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_ReportEventA, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_REPORTEVENTA, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_ReportEventA(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_ReportEventA *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_ReportEventA_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_ReportEventA, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_RegisterClusterSvc_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_RegisterClusterSvc *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_RegisterClusterSvc, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_REGISTERCLUSTERSVC, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_RegisterClusterSvc(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_RegisterClusterSvc *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_RegisterClusterSvc_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_RegisterClusterSvc, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_DeregisterClusterSvc_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_DeregisterClusterSvc *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_DeregisterClusterSvc, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_DEREGISTERCLUSTERSVC, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_DeregisterClusterSvc(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_DeregisterClusterSvc *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_DeregisterClusterSvc_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_DeregisterClusterSvc, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_WriteClusterEvents_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_WriteClusterEvents *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_WriteClusterEvents, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_WRITECLUSTEREVENTS, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_WriteClusterEvents(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_WriteClusterEvents *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_WriteClusterEvents_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_WriteClusterEvents, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_GetLogIntormation_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_GetLogIntormation *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_GetLogIntormation, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_GETLOGINTORMATION, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_GetLogIntormation(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_GetLogIntormation *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_GetLogIntormation_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_GetLogIntormation, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_eventlog_FlushEventLog_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_FlushEventLog *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(eventlog_FlushEventLog, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_eventlog, DCERPC_EVENTLOG_FLUSHEVENTLOG, mem_ctx, r);
}

NTSTATUS dcerpc_eventlog_FlushEventLog(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct eventlog_FlushEventLog *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_eventlog_FlushEventLog_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(eventlog_FlushEventLog, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}
