/* parser auto-generated by pidl */

#include "includes.h"
#include "libcli/util/nterr.h"
#include "librpc/gen_ndr/ndr_misc.h"
#include "librpc/gen_ndr/ndr_dcerpc.h"
#include "librpc/rpc/dcerpc.h"
#include "librpc/gen_ndr/ndr_dbgidl.h"

static NTSTATUS ndr_push_dummy_dbgidl(struct ndr_push *ndr, int flags, const struct dummy_dbgidl *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_dummy_dbgidl(struct ndr_pull *ndr, int flags, struct dummy_dbgidl *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_dummy_dbgidl(struct ndr_print *ndr, const char *name, int flags, const struct dummy_dbgidl *r)
{
	ndr_print_struct(ndr, name, "dummy_dbgidl");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "dummy_dbgidl");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "dummy_dbgidl");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static const struct dcerpc_interface_call dbgidl_calls[] = {
	{
		"dummy_dbgidl",
		sizeof(struct dummy_dbgidl),
		(ndr_push_flags_fn_t) ndr_push_dummy_dbgidl,
		(ndr_pull_flags_fn_t) ndr_pull_dummy_dbgidl,
		(ndr_print_function_t) ndr_print_dummy_dbgidl,
		False,
	},
	{ NULL, 0, NULL, NULL, NULL, False }
};

static const char * const dbgidl_endpoint_strings[] = {
	"ncacn_np:[\\pipe\\dbgidl]", 
};

static const struct dcerpc_endpoint_list dbgidl_endpoints = {
	.count	= 1,
	.names	= dbgidl_endpoint_strings
};

static const char * const dbgidl_authservice_strings[] = {
	"host", 
};

static const struct dcerpc_authservice_list dbgidl_authservices = {
	.count	= 1,
	.names	= dbgidl_authservice_strings
};


const struct dcerpc_interface_table dcerpc_table_dbgidl = {
	.name		= "dbgidl",
	.syntax_id	= {
		{0x1d55b526,0xc137,0x46c5,{0xab,0x79},{0x63,0x8f,0x2a,0x68,0xe8,0x69}},
		DCERPC_DBGIDL_VERSION
	},
	.helpstring	= DCERPC_DBGIDL_HELPSTRING,
	.num_calls	= 1,
	.calls		= dbgidl_calls,
	.endpoints	= &dbgidl_endpoints,
	.authservices	= &dbgidl_authservices
};

