/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_samr.h"
#include "librpc/gen_ndr/ndr_samr_c.h"

/* samr - client functions generated by pidl */


struct rpc_request *dcerpc_samr_Connect_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_Connect, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CONNECT, mem_ctx, r);
}

NTSTATUS dcerpc_samr_Connect(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_Connect_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_Connect, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_Close_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Close *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_Close, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CLOSE, mem_ctx, r);
}

NTSTATUS dcerpc_samr_Close(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Close *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_Close_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_Close, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetSecurity_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetSecurity *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetSecurity, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETSECURITY, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetSecurity(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetSecurity *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetSecurity_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetSecurity, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QuerySecurity_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QuerySecurity *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QuerySecurity, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYSECURITY, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QuerySecurity(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QuerySecurity *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QuerySecurity_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QuerySecurity, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_Shutdown_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Shutdown *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_Shutdown, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SHUTDOWN, mem_ctx, r);
}

NTSTATUS dcerpc_samr_Shutdown(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Shutdown *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_Shutdown_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_Shutdown, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_LookupDomain_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_LookupDomain *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_LookupDomain, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_LOOKUPDOMAIN, mem_ctx, r);
}

NTSTATUS dcerpc_samr_LookupDomain(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_LookupDomain *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_LookupDomain_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_LookupDomain, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_EnumDomains_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomains *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_EnumDomains, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_ENUMDOMAINS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_EnumDomains(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomains *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_EnumDomains_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_EnumDomains, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_OpenDomain_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenDomain *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_OpenDomain, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_OPENDOMAIN, mem_ctx, r);
}

NTSTATUS dcerpc_samr_OpenDomain(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenDomain *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_OpenDomain_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_OpenDomain, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryDomainInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDomainInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryDomainInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYDOMAININFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryDomainInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDomainInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryDomainInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryDomainInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetDomainInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetDomainInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetDomainInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETDOMAININFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetDomainInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetDomainInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetDomainInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetDomainInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_CreateDomainGroup_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateDomainGroup *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_CreateDomainGroup, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CREATEDOMAINGROUP, mem_ctx, r);
}

NTSTATUS dcerpc_samr_CreateDomainGroup(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateDomainGroup *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_CreateDomainGroup_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_CreateDomainGroup, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_EnumDomainGroups_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomainGroups *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_EnumDomainGroups, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_ENUMDOMAINGROUPS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_EnumDomainGroups(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomainGroups *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_EnumDomainGroups_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_EnumDomainGroups, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_CreateUser_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateUser *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_CreateUser, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CREATEUSER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_CreateUser(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateUser *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_CreateUser_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_CreateUser, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_EnumDomainUsers_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomainUsers *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_EnumDomainUsers, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_ENUMDOMAINUSERS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_EnumDomainUsers(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomainUsers *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_EnumDomainUsers_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_EnumDomainUsers, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_CreateDomAlias_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateDomAlias *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_CreateDomAlias, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CREATEDOMALIAS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_CreateDomAlias(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateDomAlias *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_CreateDomAlias_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_CreateDomAlias, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_EnumDomainAliases_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomainAliases *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_EnumDomainAliases, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_ENUMDOMAINALIASES, mem_ctx, r);
}

NTSTATUS dcerpc_samr_EnumDomainAliases(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_EnumDomainAliases *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_EnumDomainAliases_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_EnumDomainAliases, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetAliasMembership_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetAliasMembership *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetAliasMembership, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETALIASMEMBERSHIP, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetAliasMembership(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetAliasMembership *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetAliasMembership_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetAliasMembership, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_LookupNames_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_LookupNames *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_LookupNames, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_LOOKUPNAMES, mem_ctx, r);
}

NTSTATUS dcerpc_samr_LookupNames(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_LookupNames *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_LookupNames_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_LookupNames, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_LookupRids_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_LookupRids *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_LookupRids, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_LOOKUPRIDS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_LookupRids(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_LookupRids *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_LookupRids_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_LookupRids, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_OpenGroup_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenGroup *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_OpenGroup, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_OPENGROUP, mem_ctx, r);
}

NTSTATUS dcerpc_samr_OpenGroup(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenGroup *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_OpenGroup_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_OpenGroup, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryGroupInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryGroupInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryGroupInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYGROUPINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryGroupInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryGroupInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryGroupInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryGroupInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetGroupInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetGroupInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetGroupInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETGROUPINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetGroupInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetGroupInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetGroupInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetGroupInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_AddGroupMember_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_AddGroupMember *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_AddGroupMember, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_ADDGROUPMEMBER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_AddGroupMember(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_AddGroupMember *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_AddGroupMember_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_AddGroupMember, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_DeleteDomainGroup_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteDomainGroup *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_DeleteDomainGroup, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_DELETEDOMAINGROUP, mem_ctx, r);
}

NTSTATUS dcerpc_samr_DeleteDomainGroup(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteDomainGroup *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_DeleteDomainGroup_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_DeleteDomainGroup, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_DeleteGroupMember_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteGroupMember *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_DeleteGroupMember, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_DELETEGROUPMEMBER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_DeleteGroupMember(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteGroupMember *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_DeleteGroupMember_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_DeleteGroupMember, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryGroupMember_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryGroupMember *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryGroupMember, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYGROUPMEMBER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryGroupMember(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryGroupMember *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryGroupMember_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryGroupMember, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetMemberAttributesOfGroup_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetMemberAttributesOfGroup *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetMemberAttributesOfGroup, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETMEMBERATTRIBUTESOFGROUP, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetMemberAttributesOfGroup(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetMemberAttributesOfGroup *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetMemberAttributesOfGroup_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetMemberAttributesOfGroup, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_OpenAlias_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenAlias *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_OpenAlias, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_OPENALIAS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_OpenAlias(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenAlias *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_OpenAlias_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_OpenAlias, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryAliasInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryAliasInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryAliasInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYALIASINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryAliasInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryAliasInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryAliasInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryAliasInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetAliasInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetAliasInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetAliasInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETALIASINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetAliasInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetAliasInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetAliasInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetAliasInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_DeleteDomAlias_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteDomAlias *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_DeleteDomAlias, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_DELETEDOMALIAS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_DeleteDomAlias(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteDomAlias *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_DeleteDomAlias_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_DeleteDomAlias, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_AddAliasMember_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_AddAliasMember *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_AddAliasMember, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_ADDALIASMEMBER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_AddAliasMember(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_AddAliasMember *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_AddAliasMember_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_AddAliasMember, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_DeleteAliasMember_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteAliasMember *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_DeleteAliasMember, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_DELETEALIASMEMBER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_DeleteAliasMember(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteAliasMember *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_DeleteAliasMember_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_DeleteAliasMember, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetMembersInAlias_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetMembersInAlias *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetMembersInAlias, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETMEMBERSINALIAS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetMembersInAlias(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetMembersInAlias *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetMembersInAlias_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetMembersInAlias, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_OpenUser_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenUser *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_OpenUser, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_OPENUSER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_OpenUser(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OpenUser *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_OpenUser_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_OpenUser, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_DeleteUser_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteUser *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_DeleteUser, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_DELETEUSER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_DeleteUser(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_DeleteUser *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_DeleteUser_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_DeleteUser, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryUserInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryUserInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryUserInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYUSERINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryUserInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryUserInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryUserInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryUserInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetUserInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetUserInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetUserInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETUSERINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetUserInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetUserInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetUserInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetUserInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_ChangePasswordUser_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ChangePasswordUser *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_ChangePasswordUser, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CHANGEPASSWORDUSER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_ChangePasswordUser(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ChangePasswordUser *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_ChangePasswordUser_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_ChangePasswordUser, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetGroupsForUser_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetGroupsForUser *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetGroupsForUser, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETGROUPSFORUSER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetGroupsForUser(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetGroupsForUser *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetGroupsForUser_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetGroupsForUser, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryDisplayInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDisplayInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryDisplayInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYDISPLAYINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryDisplayInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDisplayInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryDisplayInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryDisplayInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetDisplayEnumerationIndex_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetDisplayEnumerationIndex *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetDisplayEnumerationIndex, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETDISPLAYENUMERATIONINDEX, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetDisplayEnumerationIndex(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetDisplayEnumerationIndex *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetDisplayEnumerationIndex_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetDisplayEnumerationIndex, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_TestPrivateFunctionsDomain_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_TestPrivateFunctionsDomain *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_TestPrivateFunctionsDomain, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_TESTPRIVATEFUNCTIONSDOMAIN, mem_ctx, r);
}

NTSTATUS dcerpc_samr_TestPrivateFunctionsDomain(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_TestPrivateFunctionsDomain *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_TestPrivateFunctionsDomain_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_TestPrivateFunctionsDomain, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_TestPrivateFunctionsUser_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_TestPrivateFunctionsUser *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_TestPrivateFunctionsUser, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_TESTPRIVATEFUNCTIONSUSER, mem_ctx, r);
}

NTSTATUS dcerpc_samr_TestPrivateFunctionsUser(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_TestPrivateFunctionsUser *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_TestPrivateFunctionsUser_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_TestPrivateFunctionsUser, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetUserPwInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetUserPwInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetUserPwInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETUSERPWINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetUserPwInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetUserPwInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetUserPwInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetUserPwInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_RemoveMemberFromForeignDomain_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_RemoveMemberFromForeignDomain *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_RemoveMemberFromForeignDomain, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_REMOVEMEMBERFROMFOREIGNDOMAIN, mem_ctx, r);
}

NTSTATUS dcerpc_samr_RemoveMemberFromForeignDomain(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_RemoveMemberFromForeignDomain *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_RemoveMemberFromForeignDomain_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_RemoveMemberFromForeignDomain, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryDomainInfo2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDomainInfo2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryDomainInfo2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYDOMAININFO2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryDomainInfo2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDomainInfo2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryDomainInfo2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryDomainInfo2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryUserInfo2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryUserInfo2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryUserInfo2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYUSERINFO2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryUserInfo2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryUserInfo2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryUserInfo2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryUserInfo2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryDisplayInfo2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDisplayInfo2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryDisplayInfo2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYDISPLAYINFO2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryDisplayInfo2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDisplayInfo2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryDisplayInfo2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryDisplayInfo2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetDisplayEnumerationIndex2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetDisplayEnumerationIndex2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetDisplayEnumerationIndex2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETDISPLAYENUMERATIONINDEX2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetDisplayEnumerationIndex2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetDisplayEnumerationIndex2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetDisplayEnumerationIndex2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetDisplayEnumerationIndex2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_CreateUser2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateUser2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_CreateUser2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CREATEUSER2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_CreateUser2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_CreateUser2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_CreateUser2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_CreateUser2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_QueryDisplayInfo3_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDisplayInfo3 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_QueryDisplayInfo3, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_QUERYDISPLAYINFO3, mem_ctx, r);
}

NTSTATUS dcerpc_samr_QueryDisplayInfo3(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_QueryDisplayInfo3 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_QueryDisplayInfo3_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_QueryDisplayInfo3, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_AddMultipleMembersToAlias_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_AddMultipleMembersToAlias *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_AddMultipleMembersToAlias, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_ADDMULTIPLEMEMBERSTOALIAS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_AddMultipleMembersToAlias(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_AddMultipleMembersToAlias *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_AddMultipleMembersToAlias_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_AddMultipleMembersToAlias, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_RemoveMultipleMembersFromAlias_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_RemoveMultipleMembersFromAlias *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_RemoveMultipleMembersFromAlias, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_REMOVEMULTIPLEMEMBERSFROMALIAS, mem_ctx, r);
}

NTSTATUS dcerpc_samr_RemoveMultipleMembersFromAlias(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_RemoveMultipleMembersFromAlias *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_RemoveMultipleMembersFromAlias_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_RemoveMultipleMembersFromAlias, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_OemChangePasswordUser2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OemChangePasswordUser2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_OemChangePasswordUser2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_OEMCHANGEPASSWORDUSER2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_OemChangePasswordUser2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_OemChangePasswordUser2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_OemChangePasswordUser2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_OemChangePasswordUser2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_ChangePasswordUser2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ChangePasswordUser2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_ChangePasswordUser2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CHANGEPASSWORDUSER2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_ChangePasswordUser2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ChangePasswordUser2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_ChangePasswordUser2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_ChangePasswordUser2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetDomPwInfo_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetDomPwInfo *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetDomPwInfo, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETDOMPWINFO, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetDomPwInfo(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetDomPwInfo *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetDomPwInfo_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetDomPwInfo, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_Connect2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_Connect2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CONNECT2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_Connect2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_Connect2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_Connect2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetUserInfo2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetUserInfo2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetUserInfo2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETUSERINFO2, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetUserInfo2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetUserInfo2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetUserInfo2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetUserInfo2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetBootKeyInformation_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetBootKeyInformation *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetBootKeyInformation, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETBOOTKEYINFORMATION, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetBootKeyInformation(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetBootKeyInformation *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetBootKeyInformation_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetBootKeyInformation, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_GetBootKeyInformation_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetBootKeyInformation *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_GetBootKeyInformation, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_GETBOOTKEYINFORMATION, mem_ctx, r);
}

NTSTATUS dcerpc_samr_GetBootKeyInformation(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_GetBootKeyInformation *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_GetBootKeyInformation_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_GetBootKeyInformation, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_Connect3_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect3 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_Connect3, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CONNECT3, mem_ctx, r);
}

NTSTATUS dcerpc_samr_Connect3(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect3 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_Connect3_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_Connect3, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_Connect4_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect4 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_Connect4, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CONNECT4, mem_ctx, r);
}

NTSTATUS dcerpc_samr_Connect4(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect4 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_Connect4_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_Connect4, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_ChangePasswordUser3_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ChangePasswordUser3 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_ChangePasswordUser3, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CHANGEPASSWORDUSER3, mem_ctx, r);
}

NTSTATUS dcerpc_samr_ChangePasswordUser3(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ChangePasswordUser3 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_ChangePasswordUser3_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_ChangePasswordUser3, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_Connect5_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect5 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_Connect5, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_CONNECT5, mem_ctx, r);
}

NTSTATUS dcerpc_samr_Connect5(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_Connect5 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_Connect5_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_Connect5, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_RidToSid_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_RidToSid *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_RidToSid, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_RIDTOSID, mem_ctx, r);
}

NTSTATUS dcerpc_samr_RidToSid(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_RidToSid *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_RidToSid_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_RidToSid, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_SetDsrmPassword_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetDsrmPassword *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_SetDsrmPassword, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_SETDSRMPASSWORD, mem_ctx, r);
}

NTSTATUS dcerpc_samr_SetDsrmPassword(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_SetDsrmPassword *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_SetDsrmPassword_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_SetDsrmPassword, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_samr_ValidatePassword_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ValidatePassword *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(samr_ValidatePassword, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_samr, DCERPC_SAMR_VALIDATEPASSWORD, mem_ctx, r);
}

NTSTATUS dcerpc_samr_ValidatePassword(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct samr_ValidatePassword *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_samr_ValidatePassword_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(samr_ValidatePassword, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}
