/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_dcerpc.h"
#include "librpc/gen_ndr/ndr_dcerpc_c.h"

/* dcerpc - client functions generated by pidl */

