/* parser auto-generated by pidl */

#include "includes.h"
#include "libcli/util/nterr.h"
#include "librpc/gen_ndr/ndr_misc.h"
#include "librpc/gen_ndr/ndr_dcerpc.h"
#include "librpc/rpc/dcerpc.h"
#include "librpc/gen_ndr/ndr_browser.h"

static NTSTATUS ndr_push_BrowserrServerEnum(struct ndr_push *ndr, int flags, const struct BrowserrServerEnum *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrServerEnum(struct ndr_pull *ndr, int flags, struct BrowserrServerEnum *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrServerEnum(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrServerEnum *r)
{
	ndr_print_struct(ndr, name, "BrowserrServerEnum");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrServerEnum");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrServerEnum");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrDebugCall(struct ndr_push *ndr, int flags, const struct BrowserrDebugCall *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrDebugCall(struct ndr_pull *ndr, int flags, struct BrowserrDebugCall *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrDebugCall(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrDebugCall *r)
{
	ndr_print_struct(ndr, name, "BrowserrDebugCall");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrDebugCall");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrDebugCall");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrQueryOtherDomains(struct ndr_push *ndr, int flags, const struct BrowserrQueryOtherDomains *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrQueryOtherDomains(struct ndr_pull *ndr, int flags, struct BrowserrQueryOtherDomains *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrQueryOtherDomains(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrQueryOtherDomains *r)
{
	ndr_print_struct(ndr, name, "BrowserrQueryOtherDomains");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrQueryOtherDomains");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrQueryOtherDomains");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrResetNetlogonState(struct ndr_push *ndr, int flags, const struct BrowserrResetNetlogonState *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrResetNetlogonState(struct ndr_pull *ndr, int flags, struct BrowserrResetNetlogonState *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrResetNetlogonState(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrResetNetlogonState *r)
{
	ndr_print_struct(ndr, name, "BrowserrResetNetlogonState");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrResetNetlogonState");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrResetNetlogonState");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrDebugTrace(struct ndr_push *ndr, int flags, const struct BrowserrDebugTrace *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrDebugTrace(struct ndr_pull *ndr, int flags, struct BrowserrDebugTrace *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrDebugTrace(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrDebugTrace *r)
{
	ndr_print_struct(ndr, name, "BrowserrDebugTrace");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrDebugTrace");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrDebugTrace");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrQueryStatistics(struct ndr_push *ndr, int flags, const struct BrowserrQueryStatistics *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrQueryStatistics(struct ndr_pull *ndr, int flags, struct BrowserrQueryStatistics *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrQueryStatistics(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrQueryStatistics *r)
{
	ndr_print_struct(ndr, name, "BrowserrQueryStatistics");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrQueryStatistics");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrQueryStatistics");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserResetStatistics(struct ndr_push *ndr, int flags, const struct BrowserResetStatistics *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserResetStatistics(struct ndr_pull *ndr, int flags, struct BrowserResetStatistics *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserResetStatistics(struct ndr_print *ndr, const char *name, int flags, const struct BrowserResetStatistics *r)
{
	ndr_print_struct(ndr, name, "BrowserResetStatistics");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserResetStatistics");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserResetStatistics");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_NetrBrowserStatisticsClear(struct ndr_push *ndr, int flags, const struct NetrBrowserStatisticsClear *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_NetrBrowserStatisticsClear(struct ndr_pull *ndr, int flags, struct NetrBrowserStatisticsClear *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_NetrBrowserStatisticsClear(struct ndr_print *ndr, const char *name, int flags, const struct NetrBrowserStatisticsClear *r)
{
	ndr_print_struct(ndr, name, "NetrBrowserStatisticsClear");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "NetrBrowserStatisticsClear");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "NetrBrowserStatisticsClear");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_NetrBrowserStatisticsGet(struct ndr_push *ndr, int flags, const struct NetrBrowserStatisticsGet *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_NetrBrowserStatisticsGet(struct ndr_pull *ndr, int flags, struct NetrBrowserStatisticsGet *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_NetrBrowserStatisticsGet(struct ndr_print *ndr, const char *name, int flags, const struct NetrBrowserStatisticsGet *r)
{
	ndr_print_struct(ndr, name, "NetrBrowserStatisticsGet");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "NetrBrowserStatisticsGet");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "NetrBrowserStatisticsGet");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrSetNetlogonState(struct ndr_push *ndr, int flags, const struct BrowserrSetNetlogonState *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrSetNetlogonState(struct ndr_pull *ndr, int flags, struct BrowserrSetNetlogonState *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrSetNetlogonState(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrSetNetlogonState *r)
{
	ndr_print_struct(ndr, name, "BrowserrSetNetlogonState");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrSetNetlogonState");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrSetNetlogonState");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrQueryEmulatedDomains(struct ndr_push *ndr, int flags, const struct BrowserrQueryEmulatedDomains *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrQueryEmulatedDomains(struct ndr_pull *ndr, int flags, struct BrowserrQueryEmulatedDomains *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrQueryEmulatedDomains(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrQueryEmulatedDomains *r)
{
	ndr_print_struct(ndr, name, "BrowserrQueryEmulatedDomains");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrQueryEmulatedDomains");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrQueryEmulatedDomains");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_BrowserrServerEnumEx(struct ndr_push *ndr, int flags, const struct BrowserrServerEnumEx *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_push_NTSTATUS(ndr, NDR_SCALARS, r->out.result));
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_BrowserrServerEnumEx(struct ndr_pull *ndr, int flags, struct BrowserrServerEnumEx *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
		NDR_CHECK(ndr_pull_NTSTATUS(ndr, NDR_SCALARS, &r->out.result));
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_BrowserrServerEnumEx(struct ndr_print *ndr, const char *name, int flags, const struct BrowserrServerEnumEx *r)
{
	ndr_print_struct(ndr, name, "BrowserrServerEnumEx");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "BrowserrServerEnumEx");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "BrowserrServerEnumEx");
		ndr->depth++;
		ndr_print_NTSTATUS(ndr, "result", r->out.result);
		ndr->depth--;
	}
	ndr->depth--;
}

static const struct dcerpc_interface_call browser_calls[] = {
	{
		"BrowserrServerEnum",
		sizeof(struct BrowserrServerEnum),
		(ndr_push_flags_fn_t) ndr_push_BrowserrServerEnum,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrServerEnum,
		(ndr_print_function_t) ndr_print_BrowserrServerEnum,
		False,
	},
	{
		"BrowserrDebugCall",
		sizeof(struct BrowserrDebugCall),
		(ndr_push_flags_fn_t) ndr_push_BrowserrDebugCall,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrDebugCall,
		(ndr_print_function_t) ndr_print_BrowserrDebugCall,
		False,
	},
	{
		"BrowserrQueryOtherDomains",
		sizeof(struct BrowserrQueryOtherDomains),
		(ndr_push_flags_fn_t) ndr_push_BrowserrQueryOtherDomains,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrQueryOtherDomains,
		(ndr_print_function_t) ndr_print_BrowserrQueryOtherDomains,
		False,
	},
	{
		"BrowserrResetNetlogonState",
		sizeof(struct BrowserrResetNetlogonState),
		(ndr_push_flags_fn_t) ndr_push_BrowserrResetNetlogonState,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrResetNetlogonState,
		(ndr_print_function_t) ndr_print_BrowserrResetNetlogonState,
		False,
	},
	{
		"BrowserrDebugTrace",
		sizeof(struct BrowserrDebugTrace),
		(ndr_push_flags_fn_t) ndr_push_BrowserrDebugTrace,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrDebugTrace,
		(ndr_print_function_t) ndr_print_BrowserrDebugTrace,
		False,
	},
	{
		"BrowserrQueryStatistics",
		sizeof(struct BrowserrQueryStatistics),
		(ndr_push_flags_fn_t) ndr_push_BrowserrQueryStatistics,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrQueryStatistics,
		(ndr_print_function_t) ndr_print_BrowserrQueryStatistics,
		False,
	},
	{
		"BrowserResetStatistics",
		sizeof(struct BrowserResetStatistics),
		(ndr_push_flags_fn_t) ndr_push_BrowserResetStatistics,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserResetStatistics,
		(ndr_print_function_t) ndr_print_BrowserResetStatistics,
		False,
	},
	{
		"NetrBrowserStatisticsClear",
		sizeof(struct NetrBrowserStatisticsClear),
		(ndr_push_flags_fn_t) ndr_push_NetrBrowserStatisticsClear,
		(ndr_pull_flags_fn_t) ndr_pull_NetrBrowserStatisticsClear,
		(ndr_print_function_t) ndr_print_NetrBrowserStatisticsClear,
		False,
	},
	{
		"NetrBrowserStatisticsGet",
		sizeof(struct NetrBrowserStatisticsGet),
		(ndr_push_flags_fn_t) ndr_push_NetrBrowserStatisticsGet,
		(ndr_pull_flags_fn_t) ndr_pull_NetrBrowserStatisticsGet,
		(ndr_print_function_t) ndr_print_NetrBrowserStatisticsGet,
		False,
	},
	{
		"BrowserrSetNetlogonState",
		sizeof(struct BrowserrSetNetlogonState),
		(ndr_push_flags_fn_t) ndr_push_BrowserrSetNetlogonState,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrSetNetlogonState,
		(ndr_print_function_t) ndr_print_BrowserrSetNetlogonState,
		False,
	},
	{
		"BrowserrQueryEmulatedDomains",
		sizeof(struct BrowserrQueryEmulatedDomains),
		(ndr_push_flags_fn_t) ndr_push_BrowserrQueryEmulatedDomains,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrQueryEmulatedDomains,
		(ndr_print_function_t) ndr_print_BrowserrQueryEmulatedDomains,
		False,
	},
	{
		"BrowserrServerEnumEx",
		sizeof(struct BrowserrServerEnumEx),
		(ndr_push_flags_fn_t) ndr_push_BrowserrServerEnumEx,
		(ndr_pull_flags_fn_t) ndr_pull_BrowserrServerEnumEx,
		(ndr_print_function_t) ndr_print_BrowserrServerEnumEx,
		False,
	},
	{ NULL, 0, NULL, NULL, NULL, False }
};

static const char * const browser_endpoint_strings[] = {
	"ncacn_np:[\\pipe\\browser]", 
	"ncacn_ip_tcp:", 
	"ncalrpc:", 
};

static const struct dcerpc_endpoint_list browser_endpoints = {
	.count	= 3,
	.names	= browser_endpoint_strings
};

static const char * const browser_authservice_strings[] = {
	"host", 
};

static const struct dcerpc_authservice_list browser_authservices = {
	.count	= 3,
	.names	= browser_authservice_strings
};


const struct dcerpc_interface_table dcerpc_table_browser = {
	.name		= "browser",
	.syntax_id	= {
		{0x6bffd098,0xa112,0x3610,{0x98,0x33},{0x01,0x28,0x92,0x02,0x01,0x62}},
		DCERPC_BROWSER_VERSION
	},
	.helpstring	= DCERPC_BROWSER_HELPSTRING,
	.num_calls	= 12,
	.calls		= browser_calls,
	.endpoints	= &browser_endpoints,
	.authservices	= &browser_authservices
};

