/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_echo.h"
#include "librpc/gen_ndr/ndr_echo_c.h"

/* rpcecho - client functions generated by pidl */


struct rpc_request *dcerpc_echo_AddOne_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_AddOne *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_AddOne, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_ADDONE, mem_ctx, r);
}

NTSTATUS dcerpc_echo_AddOne(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_AddOne *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_AddOne_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_AddOne, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_EchoData_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_EchoData *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_EchoData, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_ECHODATA, mem_ctx, r);
}

NTSTATUS dcerpc_echo_EchoData(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_EchoData *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_EchoData_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_EchoData, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_SinkData_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_SinkData *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_SinkData, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_SINKDATA, mem_ctx, r);
}

NTSTATUS dcerpc_echo_SinkData(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_SinkData *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_SinkData_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_SinkData, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_SourceData_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_SourceData *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_SourceData, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_SOURCEDATA, mem_ctx, r);
}

NTSTATUS dcerpc_echo_SourceData(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_SourceData *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_SourceData_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_SourceData, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_TestCall_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestCall *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_TestCall, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_TESTCALL, mem_ctx, r);
}

NTSTATUS dcerpc_echo_TestCall(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestCall *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_TestCall_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_TestCall, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_TestCall2_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestCall2 *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_TestCall2, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_TESTCALL2, mem_ctx, r);
}

NTSTATUS dcerpc_echo_TestCall2(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestCall2 *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_TestCall2_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_TestCall2, r);		
	}
	if (NT_STATUS_IS_OK(status)) status = r->out.result;

	return status;
}

struct rpc_request *dcerpc_echo_TestSleep_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestSleep *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_TestSleep, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_TESTSLEEP, mem_ctx, r);
}

NTSTATUS dcerpc_echo_TestSleep(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestSleep *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_TestSleep_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_TestSleep, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_TestEnum_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestEnum *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_TestEnum, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_TESTENUM, mem_ctx, r);
}

NTSTATUS dcerpc_echo_TestEnum(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestEnum *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_TestEnum_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_TestEnum, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_TestSurrounding_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestSurrounding *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_TestSurrounding, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_TESTSURROUNDING, mem_ctx, r);
}

NTSTATUS dcerpc_echo_TestSurrounding(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestSurrounding *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_TestSurrounding_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_TestSurrounding, r);		
	}

	return status;
}

struct rpc_request *dcerpc_echo_TestDoublePointer_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestDoublePointer *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(echo_TestDoublePointer, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_rpcecho, DCERPC_ECHO_TESTDOUBLEPOINTER, mem_ctx, r);
}

NTSTATUS dcerpc_echo_TestDoublePointer(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct echo_TestDoublePointer *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_echo_TestDoublePointer_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(echo_TestDoublePointer, r);		
	}

	return status;
}
