/* header auto-generated by pidl */

#include "librpc/gen_ndr/frsrpc.h"

#ifndef _HEADER_NDR_frsrpc
#define _HEADER_NDR_frsrpc

#include "librpc/ndr/libndr.h"
#define DCERPC_FRSRPC_UUID "f5cc59b4-4264-101a-8c59-08002b2f8426"
#define DCERPC_FRSRPC_VERSION 1.1
#define DCERPC_FRSRPC_NAME "frsrpc"
#define DCERPC_FRSRPC_HELPSTRING "File Replication Service"
extern const struct dcerpc_interface_table dcerpc_table_frsrpc;
NTSTATUS dcerpc_server_frsrpc_init(void);
#define DCERPC_FRSRPC_SEND_COMM_PKT (0x00)

#define DCERPC_FRSRPC_VERIFY_PROMOTION_PARENT (0x01)

#define DCERPC_FRSRPC_START_PROMOTION_PARENT (0x02)

#define DCERPC_FRSRPC_NOP (0x03)

#define DCERPC_FRSRPC_BACKUP_COMPLETE (0x04)

#define DCERPC_FRSRPC_BACKUP_COMPLETE_5 (0x05)

#define DCERPC_FRSRPC_BACKUP_COMPLETE_6 (0x06)

#define DCERPC_FRSRPC_BACKUP_COMPLETE_7 (0x07)

#define DCERPC_FRSRPC_BACKUP_COMPLETE_8 (0x08)

#define DCERPC_FRSRPC_BACKUP_COMPLETE_9 (0x09)

#define DCERPC_FRSRPC_VERIFY_PROMOTION_PARENT_EX (0x0a)

#define DCERPC_FRSRPC_CALL_COUNT (11)
void ndr_print_FRSRPC_SEND_COMM_PKT(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_SEND_COMM_PKT *r);
void ndr_print_FRSRPC_VERIFY_PROMOTION_PARENT(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_VERIFY_PROMOTION_PARENT *r);
void ndr_print_FRSRPC_START_PROMOTION_PARENT(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_START_PROMOTION_PARENT *r);
void ndr_print_FRSRPC_NOP(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_NOP *r);
void ndr_print_FRSRPC_BACKUP_COMPLETE(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE *r);
void ndr_print_FRSRPC_BACKUP_COMPLETE_5(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_5 *r);
void ndr_print_FRSRPC_BACKUP_COMPLETE_6(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_6 *r);
void ndr_print_FRSRPC_BACKUP_COMPLETE_7(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_7 *r);
void ndr_print_FRSRPC_BACKUP_COMPLETE_8(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_8 *r);
void ndr_print_FRSRPC_BACKUP_COMPLETE_9(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_9 *r);
void ndr_print_FRSRPC_VERIFY_PROMOTION_PARENT_EX(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_VERIFY_PROMOTION_PARENT_EX *r);
#endif /* _HEADER_NDR_frsrpc */
