/* header auto-generated by pidl */

#include "librpc/gen_ndr/irpc.h"

#ifndef _HEADER_NDR_irpc
#define _HEADER_NDR_irpc

#include "librpc/ndr/libndr.h"
#define DCERPC_IRPC_UUID "e770c620-0b06-4b5e-8d87-a26e20f28340"
#define DCERPC_IRPC_VERSION 1.0
#define DCERPC_IRPC_NAME "irpc"
#define DCERPC_IRPC_HELPSTRING NULL
extern const struct dcerpc_interface_table dcerpc_table_irpc;
NTSTATUS dcerpc_server_irpc_init(void);
#define DCERPC_IRPC_UPTIME (0x00)

#define DCERPC_NBTD_INFORMATION (0x01)

#define DCERPC_NBTD_GETDCNAME (0x02)

#define DCERPC_NBTD_PROXY_WINS_CHALLENGE (0x03)

#define DCERPC_NBTD_PROXY_WINS_RELEASE_DEMAND (0x04)

#define DCERPC_SMBSRV_INFORMATION (0x05)

#define DCERPC_IRPC_CALL_COUNT (6)
void ndr_print_irpc_flags(struct ndr_print *ndr, const char *name, uint32_t r);
NTSTATUS ndr_push_irpc_header(struct ndr_push *ndr, int ndr_flags, const struct irpc_header *r);
NTSTATUS ndr_pull_irpc_header(struct ndr_pull *ndr, int ndr_flags, struct irpc_header *r);
void ndr_print_irpc_header(struct ndr_print *ndr, const char *name, const struct irpc_header *r);
void ndr_print_nbtd_info_level(struct ndr_print *ndr, const char *name, enum nbtd_info_level r);
void ndr_print_nbtd_statistics(struct ndr_print *ndr, const char *name, const struct nbtd_statistics *r);
void ndr_print_nbtd_info(struct ndr_print *ndr, const char *name, const union nbtd_info *r);
void ndr_print_nbtd_proxy_wins_addr(struct ndr_print *ndr, const char *name, const struct nbtd_proxy_wins_addr *r);
void ndr_print_smbsrv_info_level(struct ndr_print *ndr, const char *name, enum smbsrv_info_level r);
void ndr_print_smbsrv_session_info(struct ndr_print *ndr, const char *name, const struct smbsrv_session_info *r);
void ndr_print_smbsrv_sessions(struct ndr_print *ndr, const char *name, const struct smbsrv_sessions *r);
void ndr_print_smbsrv_tcon_info(struct ndr_print *ndr, const char *name, const struct smbsrv_tcon_info *r);
void ndr_print_smbsrv_tcons(struct ndr_print *ndr, const char *name, const struct smbsrv_tcons *r);
void ndr_print_smbsrv_info(struct ndr_print *ndr, const char *name, const union smbsrv_info *r);
void ndr_print_irpc_uptime(struct ndr_print *ndr, const char *name, int flags, const struct irpc_uptime *r);
void ndr_print_nbtd_information(struct ndr_print *ndr, const char *name, int flags, const struct nbtd_information *r);
void ndr_print_nbtd_getdcname(struct ndr_print *ndr, const char *name, int flags, const struct nbtd_getdcname *r);
void ndr_print_nbtd_proxy_wins_challenge(struct ndr_print *ndr, const char *name, int flags, const struct nbtd_proxy_wins_challenge *r);
void ndr_print_nbtd_proxy_wins_release_demand(struct ndr_print *ndr, const char *name, int flags, const struct nbtd_proxy_wins_release_demand *r);
void ndr_print_smbsrv_information(struct ndr_print *ndr, const char *name, int flags, const struct smbsrv_information *r);
#endif /* _HEADER_NDR_irpc */
