/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_opendb.h"
#include "librpc/gen_ndr/ndr_opendb_c.h"

/* opendb - client functions generated by pidl */

