/* header auto-generated by pidl */

#include "librpc/gen_ndr/protected_storage.h"

#ifndef _HEADER_NDR_protected_storage
#define _HEADER_NDR_protected_storage

#include "librpc/ndr/libndr.h"
#define DCERPC_PROTECTED_STORAGE_UUID "c9378ff1-16f7-11d0-a0b2-00aa0061426a"
#define DCERPC_PROTECTED_STORAGE_VERSION 1.0
#define DCERPC_PROTECTED_STORAGE_NAME "protected_storage"
#define DCERPC_PROTECTED_STORAGE_HELPSTRING NULL
extern const struct dcerpc_interface_table dcerpc_table_protected_storage;
NTSTATUS dcerpc_server_protected_storage_init(void);
#define DCERPC_PS_XXX (0x00)

#define DCERPC_PROTECTED_STORAGE_CALL_COUNT (1)
void ndr_print_ps_XXX(struct ndr_print *ndr, const char *name, int flags, const struct ps_XXX *r);
#endif /* _HEADER_NDR_protected_storage */
