/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_epmapper.h"
#include "librpc/gen_ndr/ndr_epmapper_c.h"

/* epmapper - client functions generated by pidl */


struct rpc_request *dcerpc_epm_Insert_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Insert *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_Insert, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_INSERT, mem_ctx, r);
}

NTSTATUS dcerpc_epm_Insert(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Insert *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_Insert_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_Insert, r);		
	}

	return status;
}

struct rpc_request *dcerpc_epm_Delete_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Delete *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_Delete, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_DELETE, mem_ctx, r);
}

NTSTATUS dcerpc_epm_Delete(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Delete *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_Delete_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_Delete, r);		
	}

	return status;
}

struct rpc_request *dcerpc_epm_Lookup_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Lookup *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_Lookup, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_LOOKUP, mem_ctx, r);
}

NTSTATUS dcerpc_epm_Lookup(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Lookup *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_Lookup_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_Lookup, r);		
	}

	return status;
}

struct rpc_request *dcerpc_epm_Map_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Map *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_Map, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_MAP, mem_ctx, r);
}

NTSTATUS dcerpc_epm_Map(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_Map *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_Map_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_Map, r);		
	}

	return status;
}

struct rpc_request *dcerpc_epm_LookupHandleFree_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_LookupHandleFree *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_LookupHandleFree, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_LOOKUPHANDLEFREE, mem_ctx, r);
}

NTSTATUS dcerpc_epm_LookupHandleFree(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_LookupHandleFree *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_LookupHandleFree_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_LookupHandleFree, r);		
	}

	return status;
}

struct rpc_request *dcerpc_epm_InqObject_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_InqObject *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_InqObject, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_INQOBJECT, mem_ctx, r);
}

NTSTATUS dcerpc_epm_InqObject(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_InqObject *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_InqObject_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_InqObject, r);		
	}

	return status;
}

struct rpc_request *dcerpc_epm_MgmtDelete_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_MgmtDelete *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_MgmtDelete, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_MGMTDELETE, mem_ctx, r);
}

NTSTATUS dcerpc_epm_MgmtDelete(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_MgmtDelete *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_MgmtDelete_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_MgmtDelete, r);		
	}

	return status;
}

struct rpc_request *dcerpc_epm_MapAuth_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_MapAuth *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(epm_MapAuth, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_epmapper, DCERPC_EPM_MAPAUTH, mem_ctx, r);
}

NTSTATUS dcerpc_epm_MapAuth(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct epm_MapAuth *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_epm_MapAuth_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(epm_MapAuth, r);		
	}

	return status;
}
