/* client functions auto-generated by pidl */

#include "includes.h"
#include "librpc/gen_ndr/ndr_w32time.h"
#include "librpc/gen_ndr/ndr_w32time_c.h"

/* w32time - client functions generated by pidl */


struct rpc_request *dcerpc_w32time_SyncTime_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct w32time_SyncTime *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(w32time_SyncTime, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_w32time, DCERPC_W32TIME_SYNCTIME, mem_ctx, r);
}

NTSTATUS dcerpc_w32time_SyncTime(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct w32time_SyncTime *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_w32time_SyncTime_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(w32time_SyncTime, r);		
	}

	return status;
}

struct rpc_request *dcerpc_w32time_GetNetLogonServiceBits_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct w32time_GetNetLogonServiceBits *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(w32time_GetNetLogonServiceBits, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_w32time, DCERPC_W32TIME_GETNETLOGONSERVICEBITS, mem_ctx, r);
}

NTSTATUS dcerpc_w32time_GetNetLogonServiceBits(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct w32time_GetNetLogonServiceBits *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_w32time_GetNetLogonServiceBits_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(w32time_GetNetLogonServiceBits, r);		
	}

	return status;
}

struct rpc_request *dcerpc_w32time_QueryProviderStatus_send(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct w32time_QueryProviderStatus *r)
{
	if (p->conn->flags & DCERPC_DEBUG_PRINT_IN) {
		NDR_PRINT_IN_DEBUG(w32time_QueryProviderStatus, r);
	}
	
	return dcerpc_ndr_request_send(p, NULL, &dcerpc_table_w32time, DCERPC_W32TIME_QUERYPROVIDERSTATUS, mem_ctx, r);
}

NTSTATUS dcerpc_w32time_QueryProviderStatus(struct dcerpc_pipe *p, TALLOC_CTX *mem_ctx, struct w32time_QueryProviderStatus *r)
{
	struct rpc_request *req;
	NTSTATUS status;
	
	req = dcerpc_w32time_QueryProviderStatus_send(p, mem_ctx, r);
	if (req == NULL) return NT_STATUS_NO_MEMORY;

	status = dcerpc_ndr_request_recv(req);

	if (NT_STATUS_IS_OK(status) && (p->conn->flags & DCERPC_DEBUG_PRINT_OUT)) {
		NDR_PRINT_OUT_DEBUG(w32time_QueryProviderStatus, r);		
	}

	return status;
}
