/* parser auto-generated by pidl */

#include "includes.h"
#include "libcli/util/nterr.h"
#include "librpc/gen_ndr/ndr_misc.h"
#include "librpc/gen_ndr/ndr_dcerpc.h"
#include "librpc/rpc/dcerpc.h"
#include "librpc/gen_ndr/ndr_frsrpc.h"

static NTSTATUS ndr_push_FRSRPC_SEND_COMM_PKT(struct ndr_push *ndr, int flags, const struct FRSRPC_SEND_COMM_PKT *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_SEND_COMM_PKT(struct ndr_pull *ndr, int flags, struct FRSRPC_SEND_COMM_PKT *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_SEND_COMM_PKT(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_SEND_COMM_PKT *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_SEND_COMM_PKT");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_SEND_COMM_PKT");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_SEND_COMM_PKT");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_VERIFY_PROMOTION_PARENT(struct ndr_push *ndr, int flags, const struct FRSRPC_VERIFY_PROMOTION_PARENT *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_VERIFY_PROMOTION_PARENT(struct ndr_pull *ndr, int flags, struct FRSRPC_VERIFY_PROMOTION_PARENT *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_VERIFY_PROMOTION_PARENT(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_VERIFY_PROMOTION_PARENT *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_VERIFY_PROMOTION_PARENT");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_VERIFY_PROMOTION_PARENT");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_VERIFY_PROMOTION_PARENT");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_START_PROMOTION_PARENT(struct ndr_push *ndr, int flags, const struct FRSRPC_START_PROMOTION_PARENT *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_START_PROMOTION_PARENT(struct ndr_pull *ndr, int flags, struct FRSRPC_START_PROMOTION_PARENT *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_START_PROMOTION_PARENT(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_START_PROMOTION_PARENT *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_START_PROMOTION_PARENT");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_START_PROMOTION_PARENT");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_START_PROMOTION_PARENT");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_NOP(struct ndr_push *ndr, int flags, const struct FRSRPC_NOP *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_NOP(struct ndr_pull *ndr, int flags, struct FRSRPC_NOP *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_NOP(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_NOP *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_NOP");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_NOP");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_NOP");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_BACKUP_COMPLETE(struct ndr_push *ndr, int flags, const struct FRSRPC_BACKUP_COMPLETE *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_BACKUP_COMPLETE(struct ndr_pull *ndr, int flags, struct FRSRPC_BACKUP_COMPLETE *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_BACKUP_COMPLETE(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_BACKUP_COMPLETE");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_BACKUP_COMPLETE");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_BACKUP_COMPLETE");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_BACKUP_COMPLETE_5(struct ndr_push *ndr, int flags, const struct FRSRPC_BACKUP_COMPLETE_5 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_BACKUP_COMPLETE_5(struct ndr_pull *ndr, int flags, struct FRSRPC_BACKUP_COMPLETE_5 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_BACKUP_COMPLETE_5(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_5 *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_BACKUP_COMPLETE_5");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_BACKUP_COMPLETE_5");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_BACKUP_COMPLETE_5");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_BACKUP_COMPLETE_6(struct ndr_push *ndr, int flags, const struct FRSRPC_BACKUP_COMPLETE_6 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_BACKUP_COMPLETE_6(struct ndr_pull *ndr, int flags, struct FRSRPC_BACKUP_COMPLETE_6 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_BACKUP_COMPLETE_6(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_6 *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_BACKUP_COMPLETE_6");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_BACKUP_COMPLETE_6");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_BACKUP_COMPLETE_6");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_BACKUP_COMPLETE_7(struct ndr_push *ndr, int flags, const struct FRSRPC_BACKUP_COMPLETE_7 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_BACKUP_COMPLETE_7(struct ndr_pull *ndr, int flags, struct FRSRPC_BACKUP_COMPLETE_7 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_BACKUP_COMPLETE_7(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_7 *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_BACKUP_COMPLETE_7");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_BACKUP_COMPLETE_7");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_BACKUP_COMPLETE_7");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_BACKUP_COMPLETE_8(struct ndr_push *ndr, int flags, const struct FRSRPC_BACKUP_COMPLETE_8 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_BACKUP_COMPLETE_8(struct ndr_pull *ndr, int flags, struct FRSRPC_BACKUP_COMPLETE_8 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_BACKUP_COMPLETE_8(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_8 *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_BACKUP_COMPLETE_8");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_BACKUP_COMPLETE_8");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_BACKUP_COMPLETE_8");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_BACKUP_COMPLETE_9(struct ndr_push *ndr, int flags, const struct FRSRPC_BACKUP_COMPLETE_9 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_BACKUP_COMPLETE_9(struct ndr_pull *ndr, int flags, struct FRSRPC_BACKUP_COMPLETE_9 *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_BACKUP_COMPLETE_9(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_BACKUP_COMPLETE_9 *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_BACKUP_COMPLETE_9");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_BACKUP_COMPLETE_9");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_BACKUP_COMPLETE_9");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static NTSTATUS ndr_push_FRSRPC_VERIFY_PROMOTION_PARENT_EX(struct ndr_push *ndr, int flags, const struct FRSRPC_VERIFY_PROMOTION_PARENT_EX *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

static NTSTATUS ndr_pull_FRSRPC_VERIFY_PROMOTION_PARENT_EX(struct ndr_pull *ndr, int flags, struct FRSRPC_VERIFY_PROMOTION_PARENT_EX *r)
{
	if (flags & NDR_IN) {
	}
	if (flags & NDR_OUT) {
	}
	return NT_STATUS_OK;
}

_PUBLIC_ void ndr_print_FRSRPC_VERIFY_PROMOTION_PARENT_EX(struct ndr_print *ndr, const char *name, int flags, const struct FRSRPC_VERIFY_PROMOTION_PARENT_EX *r)
{
	ndr_print_struct(ndr, name, "FRSRPC_VERIFY_PROMOTION_PARENT_EX");
	ndr->depth++;
	if (flags & NDR_SET_VALUES) {
		ndr->flags |= LIBNDR_PRINT_SET_VALUES;
	}
	if (flags & NDR_IN) {
		ndr_print_struct(ndr, "in", "FRSRPC_VERIFY_PROMOTION_PARENT_EX");
		ndr->depth++;
		ndr->depth--;
	}
	if (flags & NDR_OUT) {
		ndr_print_struct(ndr, "out", "FRSRPC_VERIFY_PROMOTION_PARENT_EX");
		ndr->depth++;
		ndr->depth--;
	}
	ndr->depth--;
}

static const struct dcerpc_interface_call frsrpc_calls[] = {
	{
		"FRSRPC_SEND_COMM_PKT",
		sizeof(struct FRSRPC_SEND_COMM_PKT),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_SEND_COMM_PKT,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_SEND_COMM_PKT,
		(ndr_print_function_t) ndr_print_FRSRPC_SEND_COMM_PKT,
		False,
	},
	{
		"FRSRPC_VERIFY_PROMOTION_PARENT",
		sizeof(struct FRSRPC_VERIFY_PROMOTION_PARENT),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_VERIFY_PROMOTION_PARENT,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_VERIFY_PROMOTION_PARENT,
		(ndr_print_function_t) ndr_print_FRSRPC_VERIFY_PROMOTION_PARENT,
		False,
	},
	{
		"FRSRPC_START_PROMOTION_PARENT",
		sizeof(struct FRSRPC_START_PROMOTION_PARENT),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_START_PROMOTION_PARENT,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_START_PROMOTION_PARENT,
		(ndr_print_function_t) ndr_print_FRSRPC_START_PROMOTION_PARENT,
		False,
	},
	{
		"FRSRPC_NOP",
		sizeof(struct FRSRPC_NOP),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_NOP,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_NOP,
		(ndr_print_function_t) ndr_print_FRSRPC_NOP,
		False,
	},
	{
		"FRSRPC_BACKUP_COMPLETE",
		sizeof(struct FRSRPC_BACKUP_COMPLETE),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_BACKUP_COMPLETE,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_BACKUP_COMPLETE,
		(ndr_print_function_t) ndr_print_FRSRPC_BACKUP_COMPLETE,
		False,
	},
	{
		"FRSRPC_BACKUP_COMPLETE_5",
		sizeof(struct FRSRPC_BACKUP_COMPLETE_5),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_BACKUP_COMPLETE_5,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_BACKUP_COMPLETE_5,
		(ndr_print_function_t) ndr_print_FRSRPC_BACKUP_COMPLETE_5,
		False,
	},
	{
		"FRSRPC_BACKUP_COMPLETE_6",
		sizeof(struct FRSRPC_BACKUP_COMPLETE_6),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_BACKUP_COMPLETE_6,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_BACKUP_COMPLETE_6,
		(ndr_print_function_t) ndr_print_FRSRPC_BACKUP_COMPLETE_6,
		False,
	},
	{
		"FRSRPC_BACKUP_COMPLETE_7",
		sizeof(struct FRSRPC_BACKUP_COMPLETE_7),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_BACKUP_COMPLETE_7,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_BACKUP_COMPLETE_7,
		(ndr_print_function_t) ndr_print_FRSRPC_BACKUP_COMPLETE_7,
		False,
	},
	{
		"FRSRPC_BACKUP_COMPLETE_8",
		sizeof(struct FRSRPC_BACKUP_COMPLETE_8),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_BACKUP_COMPLETE_8,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_BACKUP_COMPLETE_8,
		(ndr_print_function_t) ndr_print_FRSRPC_BACKUP_COMPLETE_8,
		False,
	},
	{
		"FRSRPC_BACKUP_COMPLETE_9",
		sizeof(struct FRSRPC_BACKUP_COMPLETE_9),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_BACKUP_COMPLETE_9,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_BACKUP_COMPLETE_9,
		(ndr_print_function_t) ndr_print_FRSRPC_BACKUP_COMPLETE_9,
		False,
	},
	{
		"FRSRPC_VERIFY_PROMOTION_PARENT_EX",
		sizeof(struct FRSRPC_VERIFY_PROMOTION_PARENT_EX),
		(ndr_push_flags_fn_t) ndr_push_FRSRPC_VERIFY_PROMOTION_PARENT_EX,
		(ndr_pull_flags_fn_t) ndr_pull_FRSRPC_VERIFY_PROMOTION_PARENT_EX,
		(ndr_print_function_t) ndr_print_FRSRPC_VERIFY_PROMOTION_PARENT_EX,
		False,
	},
	{ NULL, 0, NULL, NULL, NULL, False }
};

static const char * const frsrpc_endpoint_strings[] = {
	"ncacn_ip_tcp:", 
	"ncalrpc:", 
};

static const struct dcerpc_endpoint_list frsrpc_endpoints = {
	.count	= 2,
	.names	= frsrpc_endpoint_strings
};

static const char * const frsrpc_authservice_strings[] = {
	"host", 
};

static const struct dcerpc_authservice_list frsrpc_authservices = {
	.count	= 2,
	.names	= frsrpc_authservice_strings
};


const struct dcerpc_interface_table dcerpc_table_frsrpc = {
	.name		= "frsrpc",
	.syntax_id	= {
		{0xf5cc59b4,0x4264,0x101a,{0x8c,0x59},{0x08,0x00,0x2b,0x2f,0x84,0x26}},
		DCERPC_FRSRPC_VERSION
	},
	.helpstring	= DCERPC_FRSRPC_HELPSTRING,
	.num_calls	= 11,
	.calls		= frsrpc_calls,
	.endpoints	= &frsrpc_endpoints,
	.authservices	= &frsrpc_authservices
};

