/* header auto-generated by pidl */

#include "librpc/gen_ndr/dcom.h"
#include "librpc/gen_ndr/orpc.h"
#ifndef _HEADER_IRemoteActivation
#define _HEADER_IRemoteActivation

#define MODE_GET_CLASS_OBJECT	( 0xffffffff )
enum imp_levels {
	RPC_C_IMP_LEVEL_DEFAULT=0,
	RPC_C_IMP_LEVEL_ANONYMOUS=1,
	RPC_C_IMP_LEVEL_IDENTIFY=2,
	RPC_C_IMP_LEVEL_IMPERSONATE=3,
	RPC_C_IMP_LEVEL_DELEGATE=4
};


struct RemoteActivation {
	struct {
		struct ORPCTHIS this;
		struct GUID Clsid;
		const char *pwszObjectName;/* [unique,string,charset(UTF16)] */
		struct MInterfacePointer *pObjectStorage;/* [unique] */
		uint32_t ClientImpLevel;
		uint32_t Mode;
		uint32_t Interfaces;/* [range(1,32768)] */
		struct GUID *pIIDs;/* [unique,size_is(Interfaces)] */
		uint16_t num_protseqs;
		uint16_t *protseq;/* [size_is(num_protseqs)] */
	} in;

	struct {
		struct ORPCTHAT *that;/* [ref] */
		uint64_t *pOxid;/* [ref] */
		struct DUALSTRINGARRAY **pdsaOxidBindings;/* [ref] */
		struct GUID *ipidRemUnknown;/* [ref] */
		uint32_t *AuthnHint;/* [ref] */
		struct COMVERSION *ServerVersion;/* [ref] */
		WERROR *hr;/* [ref] */
		struct MInterfacePointer **ifaces;/* [ref,size_is(Interfaces)] */
		WERROR *results;/* [ref,size_is(Interfaces)] */
		WERROR result;
	} out;

};

#endif /* _HEADER_IRemoteActivation */
