#ifndef __SCRIPTING_EJS_PROTO_H__
#define __SCRIPTING_EJS_PROTO_H__

#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2) PRINTF_ATTRIBUTE(a1, a2)
/* This file was automatically generated by mkproto.pl. DO NOT EDIT */

#ifndef _PUBLIC_
#define _PUBLIC_
#endif


/* The following definitions come from scripting/ejs/smbcalls.c  */

_PUBLIC_ void ejs_exception(const char *reason);
void smb_setup_ejs_functions(void (*exception_handler)(const char *));

/* The following definitions come from scripting/ejs/smbcalls_cli.c  */

void smb_setup_ejs_cli(void);

/* The following definitions come from scripting/ejs/smbcalls_rpc.c  */

int ejs_rpc_init(struct MprVar *obj, const char *name);

/* The following definitions come from scripting/ejs/smbcalls_options.c  */

void smb_setup_ejs_options(void);

/* The following definitions come from scripting/ejs/smbcalls_creds.c  */

struct MprVar mprCredentials(struct cli_credentials *creds);
int ejs_credentials_cmdline(int eid, int argc, struct MprVar **argv);
void smb_setup_ejs_credentials(void);

/* The following definitions come from scripting/ejs/smbcalls_param.c  */

struct MprVar mprParam(struct param_context *ctx);
void smb_setup_ejs_param(void);

/* The following definitions come from scripting/ejs/ejsnet.c  */

void ejsnet_setup(void);

/* The following definitions come from scripting/ejs/mprutil.c  */

struct MprVar mprObject(const char *name);
struct MprVar mprArray(const char *name);
struct MprVar mprList(const char *name, const char **list);
struct MprVar mprString(const char *s);
struct MprVar mprData(const uint8_t *p, size_t length);
struct MprVar mprLdbArray(struct ldb_context *ldb, 
			  struct ldb_message **msg, int count, const char *name);
const char *mprToString(struct MprVar *v);
int mprToInt(struct MprVar *v);
const char **mprToList(TALLOC_CTX *mem_ctx, struct MprVar *v);
const char **mprToArray(TALLOC_CTX *mem_ctx, struct MprVar *v);
struct MprVar mprNTSTATUS(NTSTATUS status);
struct MprVar mprDataBlob(DATA_BLOB blob);
struct datablob *mprToDataBlob(struct MprVar *v);
struct MprVar mprWERROR(WERROR status);
void mprSetPtr(struct MprVar *v, const char *propname, const void *p);
void mprSetPtrChild(struct MprVar *v, const char *propname, const void *p);
void *mprGetPtr(struct MprVar *v, const char *propname);
void mpr_ReturnString(int eid, const char *s);
void *mprGetThisPtr(int eid, const char *name);
void mprSetThisPtr(int eid, const char *name, void *ptr);
struct MprVar *mprInitObject(int eid, const char *name, int argc, struct MprVar **argv);

/* The following definitions come from scripting/ejs/literal.c  */

int literal_to_var(int eid, int argc, char **argv);
void smb_setup_ejs_literal(void);
#undef _PRINTF_ATTRIBUTE
#define _PRINTF_ATTRIBUTE(a1, a2)

#endif /* __SCRIPTING_EJS_PROTO_H__ */

